# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22a3ccb23b18fcce35495a2ffa8c9648bd1f1d370fec613c694a84af2cd7cbc6bc0adc74f8dbea5a059bbf1e6c0a1616e61f492ff9ef10214611cb893af1f81a

test:
  secret_key_base: 91fb9cc9b47fcb7cf751759f0cae2b4df0d89d8a097ad879dc474762658cec795d563514101006e66ce600ef27ac31bd5b0e7ebbbf7f7fcd5d39e7fe9d60f13b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
